// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppProvider: typeof import('./components/AppProvider.vue')['default']
    BetterScroll: typeof import('./components/BetterScroll.vue')['default']
    ContextMenu: typeof import('./components/ContextMenu.vue')['default']
    CountTo: typeof import('./components/CountTo.vue')['default']
    HoverContainer: typeof import('./components/HoverContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabDetail: typeof import('./components/TabDetail.vue')['default']
    VContainer: typeof import('./components/VContainer.vue')['default']
  }
}

export {}
